version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"

  api:
    container_name: api-container
    build: ./backend
    restart: always
    env_file:
      - ./docker-compose.env
    environment:
      - MONGO_URL=${MONGO_DB_URL:-mongodb://127.0.0.1:27017/tickets}
    volumes:
      - ./backend/dist:/usr/src/backend/dist
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
      - "9222:9222"
    links:
      - mongo

  frontend:
    container_name: frontend-container
    build: ./frontend
    restart: always
    ports:
      - "80:80"
